name: Semantic Release

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
      runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14.17

            - name: Install Need Dependencies
              run: yarn install

            - name: Re Building App
              run: yarn build

            - name: Tag Releases Creations
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              run: npx semantic-release
